/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package puntodeventa;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Iddot
 */
public class selecProv extends javax.swing.JInternalFrame {

    /**
     * Creates new form selecProv
     */
    public selecProv() {
        initComponents();

        cargarTabla1();

        
    }
    
    
    String nom1 = "";
    String emp1 = "";
    String tel1 = "";
    String corr1 = "";
    String prov = "";
    public static int idProv = 0;
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProvedor = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("SELECCIONA UN PROVEEDOR");

        tablaProvedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Empresa", "Telefono", "Correo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProvedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProvedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProvedor);
        if (tablaProvedor.getColumnModel().getColumnCount() > 0) {
            tablaProvedor.getColumnModel().getColumn(0).setResizable(false);
            tablaProvedor.getColumnModel().getColumn(1).setResizable(false);
            tablaProvedor.getColumnModel().getColumn(2).setResizable(false);
            tablaProvedor.getColumnModel().getColumn(3).setResizable(false);
            tablaProvedor.getColumnModel().getColumn(4).setResizable(false);
        }

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salidaText.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(238, 238, 238))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaProvedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProvedorMouseClicked
        // TODO add your handling code here:
        
        
        prov = tablaProvedor.getValueAt(tablaProvedor.getSelectedRow(), 0).toString();
        nom1 = tablaProvedor.getValueAt(tablaProvedor.getSelectedRow(), 1).toString();
        emp1 = tablaProvedor.getValueAt(tablaProvedor.getSelectedRow(), 2).toString();
        tel1 = tablaProvedor.getValueAt(tablaProvedor.getSelectedRow(), 3).toString();
        corr1 = tablaProvedor.getValueAt(tablaProvedor.getSelectedRow(), 4).toString();
        
        idProv = Integer.parseInt(prov);
        
        
        productos venProd = new productos();

        
        principal.contenedor.remove(venProd);
        
        enviar();
        
        int x = (principal.contenedor.getWidth()/2) - venProd.getWidth()/2;
        int y = (principal.contenedor.getHeight()/2) - venProd.getHeight()/2;        
        venProd.setLocation(x, y);  
        
        principal.contenedor.add(venProd);
        venProd.toFront();
        venProd.setVisible(true);
        
        
 
        
        this.dispose();
        
        
        
    }//GEN-LAST:event_tablaProvedorMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        productos venProd = new productos();
        
        int x = (principal.contenedor.getWidth()/2) - venProd.getWidth()/2;
        int y = (principal.contenedor.getHeight()/2) - venProd.getHeight()/2;        
        venProd.setLocation(x, y);  
        
        principal.contenedor.add(venProd);
        venProd.toFront();
        venProd.setVisible(true);
        
 
        this.dispose();

        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    public void cargarTabla1(){
        try {
            
            DefaultTableModel modelo = new DefaultTableModel();
            tablaProvedor.setModel(modelo);
            
            PreparedStatement ps = null;
            ResultSet rs = null;
            
            conexion conn = new conexion();
            Connection con = conn.conect();
            
            String sql = "SELECT idProveedor, Nombre, Empresa, Telefono, Correo FROM Proveedor";
            
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            
            ResultSetMetaData rsMD = rs.getMetaData();
            int cantidadColumnas = rsMD.getColumnCount();
            
            
            modelo.addColumn("Id");
            modelo.addColumn("Nombre");
            modelo.addColumn("Empresa");
            modelo.addColumn("Telefono");
            modelo.addColumn("Correo");
            
            tablaProvedor.getColumnModel().getColumn(0).setPreferredWidth(33);
            tablaProvedor.getColumnModel().getColumn(0).setResizable(false);
            tablaProvedor.getColumnModel().getColumn(1).setPreferredWidth(103);
            tablaProvedor.getColumnModel().getColumn(1).setResizable(false);
            tablaProvedor.getColumnModel().getColumn(2).setPreferredWidth(100);
            tablaProvedor.getColumnModel().getColumn(2).setResizable(false);
            tablaProvedor.getColumnModel().getColumn(3).setPreferredWidth(100);
            tablaProvedor.getColumnModel().getColumn(3).setResizable(false);
            tablaProvedor.getColumnModel().getColumn(4).setPreferredWidth(153);
            tablaProvedor.getColumnModel().getColumn(4).setResizable(false);
            
            
            

            while(rs.next()){
                
                Object[] filas = new Object[cantidadColumnas];
                
                for(int i = 0; i < cantidadColumnas; i++){
                    
                    filas[i] = rs.getObject(i + 1);
                    
                }
                
                modelo.addRow(filas);
                
            }
            
        } catch (SQLException ex) {
            
            System.err.println(ex.toString());
            
        }
    }
    
    
    
    
    public void enviar(){
        

        
        System.out.println(nom1 + emp1 + tel1 + corr1);
        
        
        productos.nomP.setText(nom1);
        productos.empP.setText(emp1);
        productos.telP.setText(tel1);
        productos.corrP.setText(corr1);
        
        
        this.dispose();
        
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tablaProvedor;
    // End of variables declaration//GEN-END:variables
}
